# Generated by Django 5.0.9 on 2024-10-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('userroleid', models.CharField(db_column='id', max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('status', models.BooleanField(db_column='Status')),
            ],
            options={
                'db_table': 'UserRole',
                'managed': True,
            },
        ),
    ]
