# Generated by Django 5.0.9 on 2024-10-19 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appuser', '0002_alter_appuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockeddatetime',
            fields=[
                ('blockeddatetimeid', models.CharField(db_column='BlockedDatetimeId', max_length=36, primary_key=True, serialize=False)),
                ('startdatetime', models.DateTimeField(db_column='StartDatetime')),
                ('enddatetime', models.DateTimeField(db_column='EndDatetime')),
                ('status', models.BooleanField(db_column='Status')),
            ],
            options={
                'db_table': 'BlockedDatetime',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentid', models.CharField(db_column='AppointmentId', max_length=36, primary_key=True, serialize=False)),
                ('startdatetime', models.DateTimeField(db_column='StartDatetime')),
                ('enddatetime', models.DateTimeField(db_column='EndDatetime')),
                ('status', models.BooleanField(db_column='Status')),
                ('appuserid', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='appuser.appuser')),
            ],
            options={
                'db_table': 'Appointment',
                'managed': True,
            },
        ),
    ]
