# Generated by Django 5.0.9 on 2024-10-20 01:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentid',
            field=models.CharField(db_column='AppointmentId', default=uuid.UUID('c7f9a705-c419-49d4-a7c5-8753668df339'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='enddatetime',
            field=models.DateTimeField(db_column='EndDatetime', unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='startdatetime',
            field=models.DateTimeField(db_column='StartDatetime', unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.BooleanField(db_column='Status', default=True),
        ),
    ]
