# Generated by Django 5.0.9 on 2024-10-19 21:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userrole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.CharField(default=uuid.UUID('526eb0db-df10-41a2-a2c9-f5f404b5114e'), max_length=36, primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_column='full_name', max_length=250)),
                ('email', models.CharField(db_column='email', max_length=250)),
                ('password', models.CharField(db_column='password', max_length=300)),
                ('userroleid', models.ForeignKey(db_column='user_role_id', on_delete=django.db.models.deletion.DO_NOTHING, to='userrole.userrole')),
            ],
            options={
                'db_table': 'AppUser',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appuser.appuser')),
            ],
            options={
                'db_table': 'PasswordResetToken',
                'managed': True,
            },
        ),
    ]
