# Generated by Django 5.0.9 on 2024-10-19 21:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.CharField(default=uuid.UUID('aea6f062-aef6-4a5a-bb50-c7ab66d1ec01'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
